## Numpy Tutorial

In [4]:
import numpy as np

Creating a scalar of value 5 

In [6]:
s = np.array(5)

View data type of s

In [10]:
s.shape

()

In [12]:
x = s + 3
x.shape

()

Creating a vector in numpy

In [14]:
v = np.array([1, 2, 3])
v.shape

(3,)

In [16]:
x = v[1]
x

2

Numpy Slicing with [ : ]

In [17]:
x = v[1:]
x

array([2, 3])

Creating matrices using np.array()

In [19]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m.shape

(3, 3)

Creating tensors - n-dimensional matrices

In [28]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [29]:
t.shape

(3, 3, 2, 1)

Changing Shapes

In [33]:
v = np.array([1,2,3,4])
v.shape

(4,)

Np.reshape( ) changes the shape of data without changing its contents

In [68]:
x= v.reshape(1,4)
x.shape

(1, 4)

## Element Wise Operation

Element-Wise Addition

In [36]:
values = [1,2,3,4,5]
values = np.array(values) + 5

In [38]:
values

array([ 6,  7,  8,  9, 10])

Setting All Elements to 0

In [40]:
values *= 0
values

array([0, 0, 0, 0, 0])

Element-Wise Multiplication

In [41]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
n = m * 0.25

In [45]:
n

array([[ 0.25,  0.5 ,  0.75],
       [ 1.  ,  1.25,  1.5 ]])

## Matrix Product (using matmul)

In [46]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
a.shape

(2, 4)

In [50]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
b.shape

(4, 3)

In [55]:
c  = np.matmul(a,b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

Matrix product using .dot( )

In [58]:
d = np.dot(a,b)
d

array([[ 70,  80,  90],
       [158, 184, 210]])

## Matrix Transpose

In [59]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Transposing Matrix

In [64]:
m.T

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

Modified Objections shared the same data

In [62]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [63]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])