In [1]:
import numpy as np

In [11]:
# Collect Data
x = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0],[1],[1],[0]])

In [12]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [13]:
x.shape

(4, 3)

In [14]:
y.shape

(4, 1)

In [15]:
# build model
num_epochs = 60000

# initialize weights with normal distribution
weights0 = 2*np.random.random((3,4)) - 1
weights1 = 2*np.random.random((4,1)) - 1

In [16]:
print(weights0)

[[ 0.18784859 -0.99007916 -0.54732227 -0.59667472]
 [ 0.1032451   0.50508164  0.8841695   0.97999198]
 [ 0.62586901  0.08909046 -0.13452778 -0.47383132]]


In [17]:
print(weights1)

[[-0.61885607]
 [ 0.49336601]
 [ 0.2198789 ]
 [-0.87949957]]


In [18]:
def sigmoid(x, deriv=False):
    #sigmoid function: squashes output probabilities with non-linearity
    if(deriv==True):
        #calculates derivative of sigmoid
        return x*(1-x)
    
    return 1/(1+np.exp(-x))

In [20]:
# train model

for j in range(num_epochs):
    #feed forward through layers 0, 1 and 2
    l0 = x #input layer
    l1 = sigmoid(np.dot(l0, weights0)) #sigmoid output of dot product btw layer 0 and weights 0
    l2 = sigmoid(np.dot(l1, weights1)) #sigmoid output of dot product btw layer 1 and weights 1
    
    l2_error = y - l2 #error for prediction
    
    if (j% 10000) == 0:
        print("Error", str(np.mean(np.abs(l2_error))))
    
    l2_delta = l2_error * sigmoid(l2, deriv=True) #error weighted gradient of output layer
    
    l1_error = l2_delta.dot(weights1.T)
    
    l1_delta = l1_error * sigmoid(l1, deriv=True)
    weights1 += l1.T.dot(l2_delta)
    weights0 += l0.T.dot(l1_delta)

Error 0.00415096485508
Error 0.00382815673895
Error 0.00356928987855
Error 0.00335578570836
Error 0.00317582708788
Error 0.00302149422474
